branches:
  only:
    - master
notifications:
  email: false
language: python
os: linux
dist: xenial
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.8"
install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install -e .
  - pip install git+https://github.com/pymanopt/pymanopt
script:
  - mkdir docs
  - cd doc
  - pip install -r requirements.txt
  # - sphinx-autogen *.rst
  - make html
  - touch _build/html/.nojekyll
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  edge: true # opt in to dpl v2
  cleanup: false
  keep_history: false
  local_dir: _build/html
  target_branch: gh-pages
  on:
      branch: master
